name: Test with Selenium and Dependency Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444
        options:
          --shm-size 2g
          --network-alias selenium-hub

      chrome:
        image: selenium/node-chrome:latest
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          NODE_MAX_SESSION: 6
          NODE_MAX_INSTANCES: 6
        options:
          --shm-size 2g
          --network-alias chrome-node

    steps:
      # Checkout code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      # Export JAVA_HOME to ensure it's accessible
      - name: Set JAVA_HOME for Dependency-Check
        run: echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Validate Dependency-Check output
      - name: List Dependency-Check Report Files
        run: ls -R ./dependency-check-report

      # Run Selenium tests
      - name: Run Selenium tests
        env:
          GRID_URL: http://selenium:4444/wd/hub
        run: mvn clean test

      # Upload Extent Reports
      - name: Upload Extent Reports
        uses: actions/upload-artifact@v3
        with:
          name: extent-reports
          path: ./Reports
